#!/usr/local/bin/python
import sys, ephem, starcalc,enoch, search

datelist = []
e = enoch.Date("-7/9/23 12:00:00")
e.prev_day(278+179)

#e = enoch.Date ( enoch.EpochDate )
#e = enoch.Date ("1977/12/19 12:00:00")
#e = enoch.Date ( "2000/2/2 15:00:00")
#e.prev_week()

rows = search.Table.day_header()
for year in range(0,364*2):
    rows += search.Table.day_row(e)
    e.next_day(1)

starcalc.Columnize.cprint ( rows )

